services:
  app:
    container_name: "backend"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - ticketing-network
    volumes:
      - ./:/app
      - /app/vendor
    depends_on:
      - postgresql
  scheduler:
    container_name: "scheduler"
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "while :; do php /app/artisan schedule:run; sleep 60; done"
    volumes:
      - .:/app
      - /app/vendor
    networks:
      - ticketing-network
  postgresql:
    image: postgres:18
    environment:
      - POSTGRES_PASSWORD=example
    networks:
      - ticketing-network
    volumes:
      - pgdata:/var/lib/postgresql

networks:
  ticketing-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
